### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by kaue** [samcday/deathbycaptcha.js#3]
```
error: Unexpected error.
    at Request._callback (/***/node_modules/deathbycaptcha/deathbycaptcha.js:98:23)
    at Request.self.callback (/***/node_modules/deathbycaptcha/node_modules/request/index.js:148:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/***/node_modules/deathbycaptcha/node_modules/request/index.js:876:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/***/node_modules/deathbycaptcha/node_modules/request/index.js:827:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

Node: v6.2.1
deathbycaptcha: v0.0.3

**Comment by samcday** [comment]
This package is very old now - perhaps DBC changed their API?

**Comment by davidpccu** [comment]
Same problem. 
It looks DBC has recently added new Node JS API
